version: '3.5'
services:
  music_library:
    build: .
    image: music_library:v01 
    restart: unless-stopped
    container_name: music_library_api
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    container_name: postgres-server
    env_file:
      - config.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: